compile:
	gcc -O2 -o main main.c 

optimized:
	gcc -O3 -o main_optimized main.c

benchmark:
	python3 benchmark.py

benchmark-extreme:
	python3 benchmark.py --extreme

benchmark-hell:
	python3 benchmark.py --hell